server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: account-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8084/realms/master}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8084/realms/master/protocol/openid-connect/certs}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banking}
    username: ${SPRING_DATASOURCE_USERNAME:banking_user}
    password: ${SPRING_DATASOURCE_PASSWORD:banking_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  pulsar:
    client:
      service-url: ${SPRING_PULSAR_CLIENT_SERVICE_URL:pulsar://localhost:6650}
    producer:
      topic-name: "persistent://public/default/account-events"
      batching-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: DEBUG
